# Generated by Django 6.1.1 on 2026-09-17 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('android_imei', 'Android (IMEI)'), ('iphone_appleid', 'iPhone (Apple ID)'), ('phone_number', 'Phone Number')], default='android_imei', max_length=30)),
                ('query_identifier', models.CharField(max_length=100, verbose_name='Target Identifier (IMEI/Phone/AppleID)')),
                ('carrier_or_brand', models.CharField(blank=True, default='', max_length=100)),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='Located', max_length=50)),
                ('accuracy_meters', models.IntegerField(default=15)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('beacon_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_live_gps', models.BooleanField(default=False, verbose_name='Verified Hardware GPS')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Tracking Record',
                'verbose_name_plural': 'Tracking Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
